(function(){
  const css=`
  :root{--br-black:#080808;--br-yellow:#ffc400;--br-white:#fff}
  .br-site-header{position:sticky;top:0;z-index:100;background:var(--br-black);color:#fff;border-bottom:1px solid #292929;font-family:Arial,Helvetica,sans-serif}
  .br-contactbar{background:#111;border-bottom:1px solid #2b2b2b;font-size:.82rem}
  .br-contactbar-inner,.br-mainbar{width:min(1180px,calc(100% - 36px));margin:auto}
  .br-contactbar-inner{min-height:32px;display:flex;align-items:center;justify-content:flex-end;gap:20px}
  .br-site-header a,.br-site-header a:visited{color:#eee;text-decoration:none}
  .br-contactbar a{font-weight:800}.br-contactbar a:hover{color:var(--br-yellow)}
  .br-mainbar{min-height:88px;display:flex;align-items:center;justify-content:space-between;gap:18px}
  .br-brand{display:flex;align-items:center;gap:16px;flex:0 0 auto;min-width:270px}
  .br-brand-symbol{display:block;width:64px;height:64px;object-fit:contain;flex:0 0 64px}
  .br-wordmark{display:flex;flex-direction:column;justify-content:center;white-space:nowrap;min-width:145px}
  .br-wordmark-main{font-family:'Arial Black',Arial,Helvetica,sans-serif;font-size:1.72rem;font-weight:900;line-height:1;letter-spacing:-.015em;color:#fff}
  .br-wordmark-main .br-b{color:var(--br-yellow)}
  .br-wordmark-sub{margin-top:8px;font-family:'Arial Black',Arial,Helvetica,sans-serif;font-size:.69rem;font-weight:900;line-height:1;letter-spacing:.34em;color:var(--br-yellow);padding-left:1px}
  .br-navright{display:flex;align-items:center;gap:12px}.br-links{display:flex;align-items:center;gap:16px;font-size:.92rem;font-weight:800}
  .br-links a:hover,.br-links a.br-active{color:var(--br-yellow)!important}
  .br-menu{position:relative}.br-menu summary{list-style:none;cursor:pointer;border:1px solid #555;border-radius:8px;padding:9px 12px;font-weight:900;color:#fff;white-space:nowrap}.br-menu summary::-webkit-details-marker{display:none}.br-menu[open] summary{border-color:var(--br-yellow);color:var(--br-yellow)}
  .br-menupanel{position:absolute;right:0;top:46px;width:310px;background:#fff;border:1px solid #d7d7d7;border-top:5px solid var(--br-yellow);border-radius:10px;box-shadow:0 16px 40px rgba(0,0,0,.28);padding:8px;z-index:120}
  .br-menupanel a,.br-menupanel a:visited{display:block;color:#111!important;padding:9px 11px;border-radius:6px;font-weight:800}.br-menupanel a:hover{background:#f2f2ef}
  .br-menupanel a.br-active{background:#fff4c2;color:#111!important;box-shadow:inset 4px 0 0 var(--br-yellow)}
  .br-sub{padding-left:25px!important;font-size:.9rem}.br-divider{height:1px;background:#e3e3e3;margin:6px 4px}
  .br-cta{background:var(--br-yellow);color:#080808!important;padding:10px 13px;border-radius:8px;font-weight:950;white-space:nowrap}
  .br-cta.br-active{box-shadow:0 0 0 2px #fff inset}
  body.br-home .hero h1{font-size:clamp(3rem,5.65vw,5.15rem)!important;line-height:1!important;letter-spacing:-.04em!important;margin:0 0 24px!important}
  body.br-home .hero h1 .br-title-line{display:block;line-height:.96;margin:0 0 .105em}
  body.br-home .hero h1 .br-title-line:last-child{margin-bottom:0}
  body.br-home .hero h1 .br-title-accent{color:var(--br-yellow)}
  body.br-home .logo-card{border:0!important;border-radius:0!important;background:transparent!important;padding:0!important;box-shadow:none!important}
  body.br-home .logo-card img{display:block!important;width:100%!important;height:auto!important;background:transparent!important}
  @media(max-width:1180px){.br-links{gap:12px;font-size:.86rem}.br-wordmark-main{font-size:1.58rem}.br-brand-symbol{width:60px;height:60px;flex-basis:60px}.br-brand{min-width:250px}}
  @media(max-width:1120px){.br-links{display:none}.br-brand{min-width:0}}
  @media(max-width:650px){.br-contactbar-inner,.br-mainbar{width:min(100% - 18px,1180px)}.br-contactbar-inner{justify-content:center;gap:12px;min-height:38px;font-size:.76rem;flex-wrap:wrap;padding:4px 0}.br-mainbar{min-height:74px;gap:7px}.br-brand{gap:10px}.br-brand-symbol{width:50px;height:50px;flex-basis:50px}.br-wordmark{min-width:0}.br-wordmark-main{font-size:1.18rem}.br-wordmark-sub{font-size:.54rem;letter-spacing:.28em;margin-top:6px}.br-cta{font-size:.69rem;padding:9px 8px}.br-menu summary{font-size:.69rem;padding:8px 8px}.br-menupanel{position:fixed;left:9px;right:9px;top:112px;width:auto;max-height:calc(100vh - 125px);overflow:auto}.br-navright{gap:6px}body.br-home .hero h1{font-size:clamp(2.75rem,12vw,4.2rem)!important}}
  @media(max-width:430px){.br-contactbar-inner{gap:8px}.br-contactbar a{font-size:.71rem}.br-brand-symbol{width:46px;height:46px;flex-basis:46px}.br-wordmark-main{font-size:1.05rem}.br-wordmark-sub{font-size:.5rem;letter-spacing:.25em}.br-cta{display:none}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const old=document.querySelector('header');if(!old)return;
  const header=document.createElement('header');header.className='br-site-header';
  header.innerHTML=`<div class="br-contactbar"><div class="br-contactbar-inner"><a href="tel:+15866463950">586-646-3950</a><a href="mailto:wayne@breadytraining.com">wayne@breadytraining.com</a></div></div><div class="br-mainbar"><a class="br-brand" href="/" aria-label="B-Ready Training home"><img class="br-brand-symbol" src="bready-symbol-transparent.png" alt=""><span class="br-wordmark"><span class="br-wordmark-main"><span class="br-b">B-</span>READY</span><span class="br-wordmark-sub">TRAINING</span></span></a><div class="br-navright"><nav class="br-links"><a data-nav="training" href="/#training">Training Overview</a><a data-nav="about" href="/#about">About</a><a data-nav="learning" href="safety-learning-hub.html">Learning Center</a><a data-nav="pricing" href="pricing.html">Pricing</a><a data-nav="reviews" href="reviews.html">Reviews</a></nav><details class="br-menu"><summary>MENU ▾</summary><div class="br-menupanel"><a data-page="home" href="/">Home</a><a data-page="training" href="/#training">Training Overview</a><a class="br-sub" data-page="pit" href="pit-forklift-training.html">PIT / Forklift — Classes I–VII</a><a class="br-sub" data-page="awp" href="awp-mewp-training.html">AWP / MEWP</a><a class="br-sub" data-page="crane" href="overhead-crane-training.html">Overhead Crane</a><a class="br-sub" data-page="trainer" href="train-the-trainer.html">Train-the-Trainer</a><div class="br-divider"></div><a data-page="about" href="/#about">About B-Ready</a><a data-page="learning" href="safety-learning-hub.html">Safety Learning Center</a><a data-page="pricing" href="pricing.html">Pricing</a><a data-page="reviews" href="reviews.html">Customer Reviews</a><a data-page="service" href="service-area.html">Service Area</a><a data-page="request" href="request-training.html">Request Training / Quote</a></div></details><a class="br-cta" data-nav="request" href="request-training.html">REQUEST TRAINING</a></div></div>`;
  old.replaceWith(header);
  const pathname=(location.pathname.split('/').pop()||'').toLowerCase();const onHome=pathname===''||pathname==='index.html';const trainingPages=['pit-forklift-training.html','awp-mewp-training.html','overhead-crane-training.html','train-the-trainer.html'];const pageMap={'pit-forklift-training.html':'pit','awp-mewp-training.html':'awp','overhead-crane-training.html':'crane','train-the-trainer.html':'trainer','safety-learning-hub.html':'learning','pricing.html':'pricing','reviews.html':'reviews','service-area.html':'service','request-training.html':'request'};
  if(onHome){document.body.classList.add('br-home');const heroTitle=document.querySelector('.hero h1');if(heroTitle){heroTitle.innerHTML='<span class="br-title-line">Train with purpose.</span><span class="br-title-line br-title-accent">B-Ready.</span><span class="br-title-line">Go home safe.</span>';}}
  function clearActive(){header.querySelectorAll('.br-active').forEach(el=>el.classList.remove('br-active'));}function mark(selector){header.querySelectorAll(selector).forEach(el=>el.classList.add('br-active'));}function setActive(){clearActive();const hash=location.hash.toLowerCase();if(onHome){if(hash==='#training'){mark('[data-nav="training"],[data-page="training"]');}else if(hash==='#about'){mark('[data-nav="about"],[data-page="about"]');}else{mark('[data-page="home"]');}return;}const key=pageMap[pathname];if(trainingPages.includes(pathname)){mark('[data-nav="training"]');}if(key){mark('[data-page="'+key+'"]');mark('[data-nav="'+key+'"]');}}
  function scrollHomeSection(hash,updateHistory){if(!onHome||!(hash==='#training'||hash==='#about'))return false;const section=document.querySelector(hash);if(!section)return false;const focus=hash==='#training'?section.querySelector('.section-head'):section.querySelector('.about-grid');const target=focus||section;const headerH=header.getBoundingClientRect().height;const breathingRoom=22;const top=target.getBoundingClientRect().top+window.scrollY-headerH-breathingRoom;window.scrollTo({top:Math.max(0,top),behavior:'smooth'});if(updateHistory)history.pushState(null,'',hash);setActive();return true;}
  header.addEventListener('click',function(e){const a=e.target.closest('a[href$="#training"],a[href$="#about"]');if(!a)return;const url=new URL(a.href,location.href);if(url.origin===location.origin&&(url.pathname==='/'||url.pathname.endsWith('/index.html'))&&onHome){e.preventDefault();scrollHomeSection(url.hash,true);const menu=header.querySelector('.br-menu');if(menu)menu.open=false;}});
  window.addEventListener('hashchange',function(){setActive();setTimeout(()=>scrollHomeSection(location.hash,false),0);});setActive();if(onHome&&(location.hash==='#training'||location.hash==='#about')){requestAnimationFrame(()=>requestAnimationFrame(()=>scrollHomeSection(location.hash,false)));}
})();